name: CI
on:
  push

env:
  NODE_ENV: ci

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: "Linting"

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.x

      - name: Set node version
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Check stale build artifacts
        run: git diff --exit-code

      - name: Lint
        run: pnpm run lint

      - name: TypeCheck
        run: pnpm run type-check

  tests:
    needs: lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: "Tests"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.x

      - name: Set node version
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm

      - name: Set GitHub Secrets as environment variables
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unit Tests with Coverage
        id: unit-tests
        run: pnpm run vitest:unit --coverage.enabled true

      - name: Run Integration Tests
        id: integration-tests
        run: pnpm run vitest:integration

      - name: Test Report
        if: always()
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "./ctrf/*.json"
          github-report: true
          annotate: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: ./vitest.unit.config.ts
