name: Deploy Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Put env variables
        run: |
          sed -i "s|__API_URL__|${{ secrets.APP_URL }}|g" docs/index.html
          sed -i "s|__API_KEY__|${{ secrets.APP_API_KEY }}|g" docs/index.html

      - name: Configure Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy Pages
        uses: actions/deploy-pages@v5
        id: deployment


